version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  faas-swagger-fn:
    lang: go
    handler: ./faas-swagger
    image: murugappans/faas-swagger-fn:v2
    secrets:
    - swagger
    - basic-auth
    environment:
      write_debug: true
