version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080
functions:
  faas-swagger-fn:
    lang: go
    handler: ./faas-swagger
    image: murugappans/faas-swagger:latest
    environment:
      openfaas_gateway: "http://gateway.openfaas:8080"
    secrets:
    - swagger    
